### ISSUE TITLE
Crash after few minutes (around 2) of video call 

### ISSUE THREAD

**Issue by suhasHere** [ethanhugg/ikran#24]
Description: 
      On running test application for more than 2 minutes the below crash was one. Call setup was done between Win32 Addon and OSx TestApp. 

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x0001e49c
[Switching to process 75302]
0xffff08d7 in __memcpy ()
(gdb) bt
#0  0xffff08d7 in __memcpy ()
#1  0x004f067e in webrtc::VCMSessionInfo::InsertBuffer (this=0x21d5264, ptrStartOfLayer=0x22cd400 "?q", packetIndex=28, packet=@0xb0516ea0) at /Users/XTM/HTML5/webrtc/trunk/src/modules/video_coding/main/source/session_info.cc:157
#2  0x004f0b18 in webrtc::VCMSessionInfo::InsertPacket (this=0x21d5264, packet=@0xb0516ea0, ptrStartOfLayer=0x22cd400 "?q") at /Users/XTM/HTML5/webrtc/trunk/src/modules/video_coding/main/source/session_info.cc:779
#3  0x004d9980 in webrtc::VCMFrameBuffer::InsertPacket (this=0x21d5200, packet=@0xb0516ea0, timeInMs=1317084246023) at /Users/XTM/HTML5/webrtc/trunk/src/modules/video_coding/main/source/frame_buffer.cc:158
#4  0x004e1088 in webrtc::VCMJitterBuffer::InsertPacket (this=0x21a8488, buffer=0x21d5204, packet=@0xb0516ea0) at /Users/XTM/HTML5/webrtc/trunk/src/modules/video_coding/main/source/jitter_buffer.cc:1688
#5  0x004ed6f6 in webrtc::VCMReceiver::InsertPacket (this=0x21a8478, packet=@0xb0516ea0, frameWidth=0, frameHeight=0) at /Users/XTM/HTML5/webrtc/trunk/src/modules/video_coding/main/source/receiver.cc:166
#6  0x004f53ec in webrtc::VideoCodingModuleImpl::IncomingPacket (this=0x21a8200, incomingPayload=0xb05175c9 "Ǚ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?~E-?\031œK\r?B?z"..., payloadLength=1435, rtpInfo=@0xb051735c) at /Users/XTM/HTML5/webrtc/trunk/src/modules/video_coding/main/source/video_coding_impl.cc:1233
#7  0x003ba4c5 in webrtc::ViEReceiver::OnReceivedPayloadData (this=0x1684c3c0, payloadData=0xb05175c9 "Ǚ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?~E-?\031œK\r?B?z"..., payloadSize=1435, rtpHeader=0xb051735c) at /Users/XTM/HTML5/webrtc/trunk/src/video_engine/main/source/vie_receiver.cc:283
#8  0x002ee6d4 in webrtc::RTPReceiver::CallbackOfReceivedPayloadData (this=0x217c99c, payloadData=0xb05175c9 "Ǚ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?~E-?\031œK\r?B?z"..., payloadSize=1435, rtpHeader=0xb051735c) at /Users/XTM/HTML5/webrtc/trunk/src/modules/rtp_rtcp/source/rtp_receiver.cc:863
#9  0x0030aea6 in webrtc::RTPReceiverVideo::ReceiveVp8Codec (this=0x217c9d4, rtpHeader=0xb051735c, payloadData=0xb05175c8 "\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?~E-?\031œK\r?B?"..., payloadDataLength=1436) at /Users/XTM/HTML5/webrtc/trunk/src/modules/rtp_rtcp/source/rtp_receiver_video.cc:651
#10 0x0030b772 in webrtc::RTPReceiverVideo::ParseVideoCodecSpecificSwitch (this=0x217c9d4, rtpHeader=0xb051735c, payloadData=0xb05175c8 "\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?~E-?\031œK\r?B?"..., payloadDataLength=1436, videoType=webrtc::kRtpVp8Video) at /Users/XTM/HTML5/webrtc/trunk/src/modules/rtp_rtcp/source/rtp_receiver_video.cc:442
#11 0x0030be69 in webrtc::RTPReceiverVideo::ParseVideoCodecSpecific (this=0x217c9d4, rtpHeader=0xb051735c, payloadData=0xb05175c8 "\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?_??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?~E-?\031œK\r?B?"..., payloadDataLength=1436, videoType=webrtc::kRtpVp8Video, isRED=false, incomingRtpPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?_??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., incomingRtpPacketSize=1448) at /Users/XTM/HTML5/webrtc/trunk/src/modules/rtp_rtcp/source/rtp_receiver_video.cc:294
#12 0x002f0a74 in webrtc::RTPReceiver::IncomingRTPPacket (this=0x217c99c, rtpHeader=0xb051735c, incomingRtpPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., incomingRtpPacketLength=1448) at /Users/XTM/HTML5/webrtc/trunk/src/modules/rtp_rtcp/source/rtp_receiver.cc:825
#13 0x002dd90c in webrtc::ModuleRtpRtcpImpl::IncomingPacket (this=0x217c600, incomingPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., incomingPacketLength=1448) at /Users/XTM/HTML5/webrtc/trunk/src/modules/rtp_rtcp/source/rtp_rtcp_impl.cc:679
#14 0x003bab1c in webrtc::ViEReceiver::InsertRTPPacket (this=0x1684c3c0, rtpPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., rtpPacketLength=1448) at /Users/XTM/HTML5/webrtc/trunk/src/video_engine/main/source/vie_receiver.cc:357
#15 0x003bac10 in webrtc::ViEReceiver::IncomingRTPPacket (this=0x1684c3c0, incomingRtpPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., incomingRtpPacketLength=1448, fromIP=0xb05174fc "10.35.132.134", fromPort=1024) at /Users/XTM/HTML5/webrtc/trunk/src/video_engine/main/source/vie_receiver.cc:219
#16 0x0036e5ee in webrtc::UdpTransportImpl::IncomingRTPFunction (this=0x216ac00, rtpPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., rtpPacketLength=1448, fromSocket=0xb0517dbc) at /Users/XTM/HTML5/webrtc/trunk/src/modules/udp_transport/source/udp_transport_impl.cc:2274
#17 0x0036e650 in webrtc::UdpTransportImpl::IncomingRTPCallback (obj=0x216ac00, rtpPacket=0xb05175bc "?x<?\022???\003\033\022G\aǙ\035{\002V??\"??\035\0365b????6\0038M??X\034\ra\005?,+?ĭ\"/K?i?6\004??6\030ME??G???C\032?O??\022\024\0051oR\035?R??\t????\005?j\016?Q?*??z??3M??R?\rx??n?L?h\b\016\0034??t??\n??\037.?tUȳ?\030??} ?\035߬?\n?q?r܃c5??-?????r?&\032'>u׳~m???;\r@#\r???(??K~?"..., rtpPacketLength=1448, from=0xb0517dbc) at /Users/XTM/HTML5/webrtc/trunk/src/modules/udp_transport/source/udp_transport_impl.cc:2200
#18 0x00373b00 in webrtc::UdpSocketPosix::HasIncoming (this=0xe4d050) at /Users/XTM/HTML5/webrtc/trunk/src/modules/udp_transport/source/udp_socket_posix.cc:206
#19 0x003748de in webrtc::UdpSocketManagerPosixImpl::Process (this=0xe27640) at /Users/XTM/HTML5/webrtc/trunk/src/modules/udp_transport/source/udp_socket_manager_posix.cc:298
#20 0x0037492f in webrtc::UdpSocketManagerPosixImpl::Run (obj=0xe27640) at /Users/XTM/HTML5/webrtc/trunk/src/modules/udp_transport/source/udp_socket_manager_posix.cc:309
#21 0x0036a17c in webrtc::ThreadPosix::Run (this=0xe277a0) at /Users/XTM/HTML5/webrtc/trunk/src/system_wrappers/source/thread_posix.cc:310
#22 0x0036a26b in StartThread (lpParameter=0xe277a0) at /Users/XTM/HTML5/webrtc/trunk/src/system_wrappers/source/thread_posix.cc:33
#23 0x92f8d85d in _pthread_start ()
#24 0x92f8d6e2 in thread_start ()

**Comment by suhasHere** [comment]
This was occurring due to mismatch in the webrtc versions. Windows had version 591 and OSX had 631. Once both were made to point to the same webrtc version, no longer this issue is seen
